#!/bin/sh
echo "xidel 0.9.9 ist erforderlich!"
echo 
echo 'wget --mirror --convert-links --backup-converted --html-extension -o wget.log https://www.prisma.io/docs/orm'
echo
cat <<EOF
find . -type f -iname '*.html' | awk '{printf "xidel --html %s --xquery \047x:replace-nodes(/, //script, function ($e) {\042 \042})\047 --output-format=html > /tmp/f && mv /tmp/f %s\n", \$0, \$0}' > f
sh -v f
EOF
echo
echo "find . -type f -iname '*.orig' -print0 | xargs -0 rm -f"
echo
echo "those were the commands"
